Dev mo fix
Itebbs22/SoftwareDevelopmentVIMMO pull request #30
Opened 2024-12-09 22:55 UTC by Mo-shalakani

minor changes:
- added error message for Panel_ID
- added comments
- Rcode can now take lowercase r
- fixed test_arg_validator

files changes:
- arg_validator
- test_arg_validator
- parser

2024-12-10 10:26 UTC, Mani-varma1 requested changes

2024-12-10 10:26 UTC, Mani-varma1 commented on vimmo/utils/arg_validator.py
> +    rcode_pattern = r"^r\d+$"
Should also accept upper case r and this pattern does not account for the upper case

2024-12-10 10:26 UTC, Mani-varma1 commented on vimmo/API/endpoints.py
Since we are accepting both lower case and upper case. This should deal with the each case accordingly and convert it to upper as the database only has upper r case stored

2024-12-12 10:08 UTC, Mani-varma1 approved these changes
Thanks for the changes.

2024-12-12 11:32 UTC, OllieGYoung approved these changes
Looks great :)

2024-12-13 13:56 UTC, Itebbs22 approved these changes

2024-12-13 14:04 UTC, merged